### ISSUE TITLE
Country detail pages with dynamic content

### ISSUE THREAD

**Issue by dsager** [Devex/research#39]
Create detail pages for countries. The content of these detail pages should be dynamically composed based on external and internal sources. 

Example data:
- [internal] recent jobs and projects located in that country
- [internal] related news articles
- [internal] top organizations and consultants with expertise in that country
- [internal] some numbers (how much funding, how many jobs)
- [external] basic info (similar to the Wikipedia-based snippet on Google search)
- [external] stats from open data sources like the world bank 
- [external] news from google, twitter etc

## Expected Outcomes and Possible Results

- Another feature, free for all our users
- Increased interlinking of content (data-wise and also visually)
- Another starting point linking to premium content
- Improved SEO

## Steps & Tasks

- Gather a list of sources
- Define UI / UX
- Implement source connectors

## Topics & Technologies

- external APIs

## Possible Follow-ups or Spin-offs

- Add more data to the countries

**Comment by kamidar** [comment]
+1 like it!

**Comment by ivandelrio** [comment]
+1

**Comment by ifosch** [comment]
### Data sources
* Internal:
  - Latest news
  - Jobs
  - Sectors
  - Contract Awards
  - Company offices
* External:
  - [Freebase](https://www.freebase.com) but take care of [this](https://plus.google.com/109936836907132434202/posts/3aYFVNf92A1)
  - [UNDP OPen Data](http://open.undp.org/) which would be interesting to find out API endpoints, instead of JSON dumps.
  - [World Bank](http://data.worldbank.org/country)
  - [Transparency International](https://www.transparency.org/)
  - [Amnesty international](https://www.amnesty.org/en/search/?q=&documentType=Annual+Report) taking special atytention on their [API](http://www.programmableweb.com/api/amnesty-international)
  - Transaparency international
  - Google News, or other reliable news sources

**Comment by ifosch** [comment]
JSON schema:
```
{
  "id": "123",
  "slug": "ecuador",
  "name": "Ecuador",
  "iso_3": "XXX",
  "iso_2": "XX",
  "meta": {},
  "news": [
    { id, slug, teaser, thumbnail, title, overline, byline, url, source }
  ],
  "stats": {},
  "companies": [],
  "jobs": [
    { id, slug, thumbnail, title, url, source }
  ]
}
```
